import React from "react";

/**
 * A deliberately small markdown renderer for release-notes pages.
 *
 * These files are machine-generated by scripts/docx-to-announcement.py, so the
 * syntax that can appear is a known, closed set: h1/h2 headings, paragraphs,
 * dash bullets, bold spans and standalone images. Rendering that subset by
 * hand is a few dozen lines and keeps a markdown library out of the bundle.
 */

const BOLD = /\*\*(.+?)\*\*/g;

/** Inline formatting: bold only, which is all the converter emits. */
function inline(text: string, keyPrefix: string): React.ReactNode[] {
  const parts: React.ReactNode[] = [];
  let last = 0;
  let m: RegExpExecArray | null;
  BOLD.lastIndex = 0;
  while ((m = BOLD.exec(text)) !== null) {
    if (m.index > last) parts.push(text.slice(last, m.index));
    parts.push(
      <strong key={`${keyPrefix}-b${m.index}`} className="text-foreground">
        {m[1]}
      </strong>,
    );
    last = m.index + m[0].length;
  }
  if (last < text.length) parts.push(text.slice(last));
  return parts;
}

export function renderMarkdown(md: string): React.ReactNode[] {
  const out: React.ReactNode[] = [];
  const lines = md.replace(/\r/g, "").split("\n");
  let bullets: string[] = [];

  const flushBullets = () => {
    if (!bullets.length) return;
    const items = bullets;
    bullets = [];
    out.push(
      <ul
        key={`ul-${out.length}`}
        className="my-5 space-y-3 border-l-2 border-white/10 pl-5"
      >
        {items.map((b, i) => (
          <li key={i} className="leading-relaxed text-muted">
            {inline(b, `li-${out.length}-${i}`)}
          </li>
        ))}
      </ul>,
    );
  };

  lines.forEach((raw, idx) => {
    const line = raw.trim();
    if (!line) {
      flushBullets();
      return;
    }

    const img = line.match(/^!\[\]\((.+?)\)$/);
    if (img) {
      flushBullets();
      out.push(
        // eslint-disable-next-line @next/next/no-img-element
        <img
          key={`img-${idx}`}
          src={img[1]}
          alt=""
          loading="lazy"
          className="my-7 w-full rounded-xl border border-white/10 shadow-lg shadow-black/40"
        />,
      );
      return;
    }

    if (line.startsWith("## ")) {
      flushBullets();
      out.push(
        <h2
          key={`h2-${idx}`}
          className="mt-14 mb-4 border-b border-white/10 pb-2 text-2xl font-semibold text-foreground"
        >
          {line.slice(3)}
        </h2>,
      );
      return;
    }

    if (line.startsWith("# ")) {
      flushBullets();
      out.push(
        <h1 key={`h1-${idx}`} className="mb-3 text-4xl font-bold text-foreground">
          {line.slice(2)}
        </h1>,
      );
      return;
    }

    if (line.startsWith("- ")) {
      bullets.push(line.slice(2));
      return;
    }

    flushBullets();
    out.push(
      <p key={`p-${idx}`} className="my-4 leading-relaxed text-muted">
        {inline(line, `p-${idx}`)}
      </p>,
    );
  });

  flushBullets();
  return out;
}
