import React from "react";

/**
 * A deliberately small markdown renderer for release-notes pages.
 *
 * These files are machine-generated by scripts/docx-to-announcement.py, or
 * adapted from the in-app announcement body, so the syntax that can appear is
 * a known, closed set: h1/h2/h3 headings, paragraphs, dash bullets, numbered
 * steps, bold spans, links, blockquote callouts and standalone images. Rendering that subset by
 * hand is a few dozen lines and keeps a markdown library out of the bundle.
 *
 * Deliberately NOT supported: horizontal rules. An h2 already carries a
 * bottom border, so a `---` beside one would double the divider.
 */

const BOLD = /\*\*(.+?)\*\*/g;
const LINK = /\[([^\]]+)\]\(([^)\s]+)\)/g;

/** Bold spans, the only inline formatting the converter emits. */
function bold(text: string, keyPrefix: string): React.ReactNode[] {
  const parts: React.ReactNode[] = [];
  let last = 0;
  let m: RegExpExecArray | null;
  BOLD.lastIndex = 0;
  while ((m = BOLD.exec(text)) !== null) {
    if (m.index > last) parts.push(text.slice(last, m.index));
    parts.push(
      <strong key={`${keyPrefix}-b${m.index}`} className="text-foreground">
        {m[1]}
      </strong>,
    );
    last = m.index + m[0].length;
  }
  if (last < text.length) parts.push(text.slice(last));
  return parts;
}

/**
 * Inline formatting: bold, plus `[text](href)` links for the hand-written
 * pages (the how-to guides point back at their release notes). Only site
 * paths and https URLs become links; anything else stays literal text.
 */
function inline(text: string, keyPrefix: string): React.ReactNode[] {
  const parts: React.ReactNode[] = [];
  let last = 0;
  let m: RegExpExecArray | null;
  LINK.lastIndex = 0;
  while ((m = LINK.exec(text)) !== null) {
    const href = m[2];
    if (!href.startsWith("/") && !href.startsWith("https://")) continue;
    if (m.index > last) parts.push(...bold(text.slice(last, m.index), `${keyPrefix}-t${last}`));
    parts.push(
      <a
        key={`${keyPrefix}-a${m.index}`}
        href={href}
        className="font-semibold text-brand-teal hover:underline"
      >
        {bold(m[1], `${keyPrefix}-al${m.index}`)}
      </a>,
    );
    last = m.index + m[0].length;
  }
  if (last < text.length) parts.push(...bold(text.slice(last), `${keyPrefix}-t${last}`));
  return parts;
}

export function renderMarkdown(md: string): React.ReactNode[] {
  const out: React.ReactNode[] = [];
  const lines = md.replace(/\r/g, "").split("\n");
  let bullets: string[] = [];
  let steps: string[] = [];

  // Numbered steps render as a numbered path of circles, for the how-to
  // guides, where the order is the whole point.
  const flushSteps = () => {
    if (!steps.length) return;
    const items = steps;
    steps = [];
    out.push(
      <ol key={`ol-${out.length}`} className="my-5 space-y-4">
        {items.map((s, i) => (
          <li key={i} className="flex gap-4 leading-relaxed text-muted">
            <span className="mt-0.5 flex h-7 w-7 flex-none items-center justify-center rounded-full bg-brand-green/15 text-sm font-bold text-brand-green ring-1 ring-brand-green/40">
              {i + 1}
            </span>
            <span className="pt-0.5">{inline(s, `ol-${out.length}-${i}`)}</span>
          </li>
        ))}
      </ol>,
    );
  };

  const flushBullets = () => {
    if (!bullets.length) return;
    const items = bullets;
    bullets = [];
    out.push(
      <ul
        key={`ul-${out.length}`}
        className="my-5 space-y-3 border-l-2 border-white/10 pl-5"
      >
        {items.map((b, i) => (
          <li key={i} className="leading-relaxed text-muted">
            {inline(b, `li-${out.length}-${i}`)}
          </li>
        ))}
      </ul>,
    );
  };

  lines.forEach((raw, idx) => {
    const line = raw.trim();
    if (!line) {
      flushBullets();
      flushSteps();
      return;
    }

    const step = line.match(/^\d+\.\s+(.*)$/);
    if (step) {
      flushBullets();
      steps.push(step[1]);
      return;
    }
    flushSteps();

    // `![](src)` is a full-width picture, as the release pages use it.
    // `![Caption](src#w=320)` adds a caption under it and caps its width,
    // for the how-to guides' tall, narrow app screenshots.
    const img = line.match(/^!\[(.*?)\]\((.+?)\)$/);
    if (img) {
      flushBullets();
      const caption = img[1];
      const [src, frag] = img[2].split("#");
      const w = frag?.match(/^w=(\d+)$/)?.[1];
      const picture = (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={src}
          alt={caption}
          loading="lazy"
          style={w ? { maxWidth: `${w}px` } : undefined}
          className={`${w ? "mx-auto " : ""}w-full rounded-xl border border-white/10 shadow-lg shadow-black/40`}
        />
      );
      out.push(
        caption || w ? (
          <figure key={`img-${idx}`} className="my-7">
            {picture}
            {caption && (
              <figcaption className="mt-3 text-center text-sm text-muted">
                {inline(caption, `cap-${idx}`)}
              </figcaption>
            )}
          </figure>
        ) : (
          <div key={`img-${idx}`} className="my-7">
            {picture}
          </div>
        ),
      );
      return;
    }

    // A callout, for the asides that qualify a feature rather than describe
    // one. Mirrors the in-app announcement card, which styles blockquote as a
    // tinted box with an accent rule.
    if (line.startsWith("> ")) {
      flushBullets();
      out.push(
        <blockquote
          key={`q-${idx}`}
          className="my-6 rounded-xl border-l-4 border-brand-teal/60 bg-brand-teal/5 px-5 py-4 leading-relaxed text-muted"
        >
          {inline(line.slice(2), `q-${idx}`)}
        </blockquote>,
      );
      return;
    }

    if (line.startsWith("### ")) {
      flushBullets();
      out.push(
        <h3
          key={`h3-${idx}`}
          className="mt-8 mb-3 text-lg font-semibold text-foreground"
        >
          {line.slice(4)}
        </h3>,
      );
      return;
    }

    if (line.startsWith("## ")) {
      flushBullets();
      out.push(
        <h2
          key={`h2-${idx}`}
          className="mt-14 mb-4 border-b border-white/10 pb-2 text-2xl font-semibold text-foreground"
        >
          {line.slice(3)}
        </h2>,
      );
      return;
    }

    if (line.startsWith("# ")) {
      flushBullets();
      out.push(
        <h1 key={`h1-${idx}`} className="mb-3 text-4xl font-bold text-foreground">
          {line.slice(2)}
        </h1>,
      );
      return;
    }

    if (line.startsWith("- ")) {
      bullets.push(line.slice(2));
      return;
    }

    flushBullets();
    out.push(
      <p key={`p-${idx}`} className="my-4 leading-relaxed text-muted">
        {inline(line, `p-${idx}`)}
      </p>,
    );
  });

  flushBullets();
  flushSteps();
  return out;
}
